config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # devise_for :useres
  devise_for :useres, controllers: { sessions: 'users/sessions' }

  resources :pedido_produtos
  resources :pedidos
  resources :produtos
  resources :clientes

  resources :alunos

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'stimulus', to: 'spa#stimulus'
  get 'jquery', to: 'spa#jquery'

  get 'csv', to: 'csv#index'
  post 'upload', to: 'csv#upload'

  Rails.application.routes.draw do
    # Outras rotas da sua aplicação
    mount Sidekiq::Web => '/sidekiq'
  end

  ## desabilitado para usar o devise
  # get 'login', to: 'login#index'
  # post 'acao-login', to: 'login#acao_login'
  # get 'sair', to: 'login#sair'
  
  get 'hotwire', to: 'spa#hotwire'
  get 'hotwire_template', to: 'spa#hotwire_template', as: 'hotwire_template'

  get 'carregando-pedaco-codigo', to: 'spa#carregando_pedaco_codigo'

  root "home#index"

  get 'fornecedores/novo', to: 'fornecedores#novo', as: 'fornecedor_novo'
  get 'fornecedores/:id/editar', to: 'fornecedores#editar', as: 'fornecedor_editar'
  #### Padrão RESTful ###
  get 'fornecedores', to: 'fornecedores#index', as: 'fornecedores'
  get 'fornecedores/:id', to: 'fornecedores#mostrar', as: 'fornecedor_mostrar'
  post 'fornecedores', to: 'fornecedores#cadastrar', as: 'fornecedor_cadastrar'
  match 'fornecedores/:id', to: 'fornecedores#alterar', as: 'fornecedor', via: [:put, :patch]
  delete 'fornecedores/:id', to: 'fornecedores#excluir', as: 'fornecedor_excluir'
  #######################
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  include BuscaPorId


  has_many :pedidos, dependent: :destroy

  # validates :nome, :telefone, presence: true
  # validates :telefone, uniqueness: true
  # validates :telefone, format: { with: /\A\(\d{2}\)\s\d{5}-\d{4}\z/, message: "deve estar no formato (00) 00000-0000" }
  # validates :nome, length: { minimum: 5, maximum: 150 }
  # validates :nome, inclusion: { in: %w(Silva Santos Felix), message: "%{value} não é um tipo de nome válido" }
  # validates :nome, inclusion: { in: ["Silva", "Santos", "Felix"], message: "%{value} não é um tipo de nome válido" }
  
  # validates :nome, exclusion: { in: %w(Matiazi Ferdinant), message: "(%{value}) de usuário não está disponível" }

  # validates :ativo, acceptance: { message: "Você precisa deixar o seu cliente ativo" }

  
  # validate :custom_validation_method



  # def custom_validation_method
  #   if !self.nome.include?("Silva") || !self.telefone.include?("(21)")
  #     self.errors.add(:telefone, "precisa conter Silva no nome e o ddd precisa ser (21)")
  #   end
  # end
end

app/models/entidades/cliente.rb
module Entidades
    class Cliente
        attr_accessor :id, :nome, :telefone, :endereco
    end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationLoginController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  include SalvarObjeto

  # GET /clientes or /clientes.json
  # def index
  #   page = params[:pagina].to_i || 1
  #   page = 1 if page < 1

  #   quantidade_por_pagina = 3

  #   offset = (page-1) * quantidade_por_pagina

  #   @clientes = Cliente.order(id: :desc).limit(quantidade_por_pagina).offset(offset)

  #   respond_to do |format|
  #     format.turbo_stream { 
  #       render turbo_stream: turbo_stream.append(:clientes, partial: 'clientes/clientes_hotwire', locals: { clientes: @clientes })
  #     }

  #     format.html { render :index }
  #   end
  # end



  def index
    repo = Repositorios::ClientesRepositorio.new

    # cliente1 = Entidades::Cliente.new
    # cliente1.nome = "Luiz"
    # cliente1.telefone = "11111111"
    # cliente1.endereco = "Rua do Luiz"

    # repo.salvar(cliente1)

    # cliente2 = Entidades::Cliente.new
    # cliente2.id = 2
    # cliente2.nome = "Luiz Santos"
    # cliente2.telefone = "11111111"
    # cliente2.endereco = "Rua do Luiz"

    # repo.salvar(cliente2)

    # cliente_erro = Entidades::Cliente.new
    # cliente_erro.telefone = "11111111"
    # cliente_erro.endereco = "Rua do Luiz"

    # begin
    #   repo.salvar!(cliente_erro)
    # rescue Servicos::Erros::ValidarErros => erro
    #   flash["error"] = "Erro na minha validação - #{erro.message}"
    #   return redirect_to "/stimulus"
    # rescue Exception => erro
    #   flash["error"] = erro.message
    #   return redirect_to "/stimulus"
    # end

    @clientes = repo.todos(params[:pagina])

    # respond_to do |format|
    #   format.turbo_stream { 
    #     render turbo_stream: turbo_stream.append(:clientes, partial: 'clientes/clientes_hotwire', locals: { clientes: @clientes })
    #   }

    #   format.html { render :index }
    # end
  end


  # def index
  #   repo = Repositorios::ClientesActiveRecordRepositorio.new(Cliente)

  #   # cliente1 = Cliente.new
  #   # cliente1.nome = "Luiz 4"
  #   # cliente1.telefone = "11111111"
  #   # cliente1.endereco = "Rua do Luiz"

  #   # repo.salvar(cliente1)

  #   # cliente2 = repo.busca_por_id(2)
  #   # cliente2.nome = "Luiz Santos"

  #   # repo.salvar(cliente2)

  #   @clientes = repo.todos(params[:pagina])

  #   respond_to do |format|
  #     format.turbo_stream { 
  #       render turbo_stream: turbo_stream.append(:clientes, partial: 'clientes/clientes_hotwire', locals: { clientes: @clientes })
  #     }

  #     format.html { render :index }
  #   end
  # end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if salvar(@cliente)
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nome, :telefone, :endereco)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_cliente.html.erb
<div id="<%= dom_id cliente %>">
  <p>
    <strong>Nome:</strong>
    <%= cliente.nome %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= cliente.telefone %>
  </p>

  <p>
    <strong>Endereco:</strong>
    <%= cliente.endereco %>
  </p>

</div>

app/views/clientes/_clientes_hotwire.turbo_stream.erb
<div>Partial</div>
<table>
    <thead>
        <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Telefone</th>
        <th>Endereço</th>
        <th></th>
        </tr>
    </thead>
    <tbody>
        <% clientes.each do |cliente| %>
        <tr>
            <td><%= cliente.id %></td>
            <td><%= cliente.nome %></td>
            <td><%= cliente.telefone %></td>
            <td><%= cliente.endereco %></td>
            <td>
            <%= link_to "Mostrar", cliente_path(cliente) %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :endereco, style: "display: block" %>
    <%= form.text_field :endereco %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<section class="panel banner right">
	<div class="content color0 span-3-75">
    <a href="/">Voltar para home</a><br>
    <h1>Editing cliente</h1>

    <%= render "form", cliente: @cliente %>

    <br>

    <div>
      <%= link_to "Show this cliente", @cliente %> |
      <%= link_to "Back to clientes", clientes_path %>
    </div>
  </div>

	<div class="image filtered span-1-75" data-position="25% 25%">
    <img src="/images/pic01.jpg" alt="" />
  </div>
</section>

app/views/clientes/index.html.erb
<section class="panel banner right">
	<div class="content color0 span-3-75">
    <a href="/">Voltar para home</a><br>
    <h1>Clientes</h1>
    <hr style="margin: 0px;">

		<%= link_to "Carregar clientes hotwire", clientes_path, 'data-turbo-frame': 'clientes' %>

		<%= turbo_frame_tag 'clientes' do %>
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>Telefone</th>
            <th>Endereço</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @clientes.each do |cliente| %>
            <tr>
              <td><%= cliente.id %></td>
              <td><%= cliente.nome %></td>
              <td><%= cliente.telefone %></td>
              <td><%= cliente.endereco %></td>
              <td>
                <%= link_to "Mostrar", cliente_path(cliente) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>

    <%= link_to "Novo Cliente", new_cliente_path %>
  </div>

	<div class="image filtered span-1-75" data-position="25% 25%">
    <img src="/images/pic01.jpg" alt="" />
  </div>
</section>

app/views/clientes/new.html.erb
<section class="panel banner right">
	<div class="content color0 span-3-75">
    <a href="/">Voltar para home</a><br>
    <h1>New cliente</h1>

    <%= render "form", cliente: @cliente %>

    <br>

    <div>
      <%= link_to "Back to clientes", clientes_path %>
    </div>
  </div>

	<div class="image filtered span-1-75" data-position="25% 25%">
    <img src="/images/pic01.jpg" alt="" />
  </div>
</section>

app/views/clientes/show.html.erb
<section class="panel banner right">
	<div class="content color0 span-3-75">
    <a href="/">Voltar para home</a><br>

    <p style="color: green"><%= notice %></p>

    <%= render @cliente %>

    <div>
      <%= link_to "Edit this cliente", edit_cliente_path(@cliente) %> |
      <%= link_to "Back to clientes", clientes_path %>

      <%= button_to "Destroy this cliente", @cliente, method: :delete %>
    </div>

  </div>

	<div class="image filtered span-1-75" data-position="25% 25%">
    <img src="/images/pic01.jpg" alt="" />
  </div>
</section>