config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # devise_for :useres
  devise_for :useres, controllers: { sessions: 'users/sessions' }

  resources :pedido_produtos
  resources :pedidos
  resources :produtos
  resources :clientes

  resources :alunos

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'stimulus', to: 'spa#stimulus'
  get 'jquery', to: 'spa#jquery'

  get 'csv', to: 'csv#index'
  post 'upload', to: 'csv#upload'

  Rails.application.routes.draw do
    # Outras rotas da sua aplicação
    mount Sidekiq::Web => '/sidekiq'
  end

  ## desabilitado para usar o devise
  # get 'login', to: 'login#index'
  # post 'acao-login', to: 'login#acao_login'
  # get 'sair', to: 'login#sair'
  
  get 'hotwire', to: 'spa#hotwire'
  get 'hotwire_template', to: 'spa#hotwire_template', as: 'hotwire_template'

  get 'carregando-pedaco-codigo', to: 'spa#carregando_pedaco_codigo'

  root "home#index"

  get 'fornecedores/novo', to: 'fornecedores#novo', as: 'fornecedor_novo'
  get 'fornecedores/:id/editar', to: 'fornecedores#editar', as: 'fornecedor_editar'
  #### Padrão RESTful ###
  get 'fornecedores', to: 'fornecedores#index', as: 'fornecedores'
  get 'fornecedores/:id', to: 'fornecedores#mostrar', as: 'fornecedor_mostrar'
  post 'fornecedores', to: 'fornecedores#cadastrar', as: 'fornecedor_cadastrar'
  match 'fornecedores/:id', to: 'fornecedores#alterar', as: 'fornecedor', via: [:put, :patch]
  delete 'fornecedores/:id', to: 'fornecedores#excluir', as: 'fornecedor_excluir'
  #######################
end

app/models/pedido_produto.rb
class PedidoProduto < ApplicationRecord
  belongs_to :pedido
  belongs_to :produto
end

app/controllers/pedido_produtos_controller.rb
class PedidoProdutosController < ApplicationLoginController
  before_action :set_pedido_produto, only: %i[ show edit update destroy ]

  # GET /pedido_produtos or /pedido_produtos.json
  def index
    @pedido_produtos = PedidoProduto.all
  end

  # GET /pedido_produtos/1 or /pedido_produtos/1.json
  def show
  end

  # GET /pedido_produtos/new
  def new
    @pedido_produto = PedidoProduto.new
  end

  # GET /pedido_produtos/1/edit
  def edit
  end

  # POST /pedido_produtos or /pedido_produtos.json
  def create
    @pedido_produto = PedidoProduto.new(pedido_produto_params)

    respond_to do |format|
      if @pedido_produto.save
        format.html { redirect_to pedido_produto_url(@pedido_produto), notice: "Pedido produto was successfully created." }
        format.json { render :show, status: :created, location: @pedido_produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pedido_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedido_produtos/1 or /pedido_produtos/1.json
  def update
    respond_to do |format|
      if @pedido_produto.update(pedido_produto_params)
        format.html { redirect_to pedido_produto_url(@pedido_produto), notice: "Pedido produto was successfully updated." }
        format.json { render :show, status: :ok, location: @pedido_produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pedido_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedido_produtos/1 or /pedido_produtos/1.json
  def destroy
    @pedido_produto.destroy

    respond_to do |format|
      format.html { redirect_to pedido_produtos_url, notice: "Pedido produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido_produto
      @pedido_produto = PedidoProduto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_produto_params
      params.require(:pedido_produto).permit(:pedido_id, :produto_id, :valor, :quantidade)
    end
end

app/helpers/pedido_produtos_helper.rb
module PedidoProdutosHelper
end

app/views/pedido_produtos/_form.html.erb
<%= form_with(model: pedido_produto) do |form| %>
  <% if pedido_produto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pedido_produto.errors.count, "error") %> prohibited this pedido_produto from being saved:</h2>

      <ul>
        <% pedido_produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :pedido_id, style: "display: block" %>
    <%= form.text_field :pedido_id %>
  </div>

  <div>
    <%= form.label :produto_id, style: "display: block" %>
    <%= form.text_field :produto_id %>
  </div>

  <div>
    <%= form.label :valor, style: "display: block" %>
    <%= form.text_field :valor %>
  </div>

  <div>
    <%= form.label :quantidade, style: "display: block" %>
    <%= form.number_field :quantidade %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pedido_produtos/_pedido_produto.html.erb
<div id="<%= dom_id pedido_produto %>">
  <p>
    <strong>Pedido:</strong>
    <%= pedido_produto.pedido_id %>
  </p>

  <p>
    <strong>Produto:</strong>
    <%= pedido_produto.produto_id %>
  </p>

  <p>
    <strong>Valor:</strong>
    <%= pedido_produto.valor %>
  </p>

  <p>
    <strong>Quantidade:</strong>
    <%= pedido_produto.quantidade %>
  </p>

</div>

app/views/pedido_produtos/edit.html.erb
<h1>Editing pedido produto</h1>

<%= render "form", pedido_produto: @pedido_produto %>

<br>

<div>
  <%= link_to "Show this pedido produto", @pedido_produto %> |
  <%= link_to "Back to pedido produtos", pedido_produtos_path %>
</div>

app/views/pedido_produtos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pedido produtos</h1>

<div id="pedido_produtos">
  <% @pedido_produtos.each do |pedido_produto| %>
    <%= render pedido_produto %>
    <p>
      <%= link_to "Show this pedido produto", pedido_produto %>
    </p>
  <% end %>
</div>

<%= link_to "New pedido produto", new_pedido_produto_path %>

app/views/pedido_produtos/new.html.erb
<h1>New pedido produto</h1>

<%= render "form", pedido_produto: @pedido_produto %>

<br>

<div>
  <%= link_to "Back to pedido produtos", pedido_produtos_path %>
</div>

app/views/pedido_produtos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pedido_produto %>

<div>
  <%= link_to "Edit this pedido produto", edit_pedido_produto_path(@pedido_produto) %> |
  <%= link_to "Back to pedido produtos", pedido_produtos_path %>

  <%= button_to "Destroy this pedido produto", @pedido_produto, method: :delete %>
</div>