config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # devise_for :useres
  devise_for :useres, controllers: { sessions: 'users/sessions' }

  resources :pedido_produtos
  resources :pedidos
  resources :produtos
  resources :clientes

  resources :alunos

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'stimulus', to: 'spa#stimulus'
  get 'jquery', to: 'spa#jquery'

  get 'csv', to: 'csv#index'
  post 'upload', to: 'csv#upload'

  Rails.application.routes.draw do
    # Outras rotas da sua aplicação
    mount Sidekiq::Web => '/sidekiq'
  end

  ## desabilitado para usar o devise
  # get 'login', to: 'login#index'
  # post 'acao-login', to: 'login#acao_login'
  # get 'sair', to: 'login#sair'
  
  get 'hotwire', to: 'spa#hotwire'
  get 'hotwire_template', to: 'spa#hotwire_template', as: 'hotwire_template'

  get 'carregando-pedaco-codigo', to: 'spa#carregando_pedaco_codigo'

  root "home#index"

  get 'fornecedores/novo', to: 'fornecedores#novo', as: 'fornecedor_novo'
  get 'fornecedores/:id/editar', to: 'fornecedores#editar', as: 'fornecedor_editar'
  #### Padrão RESTful ###
  get 'fornecedores', to: 'fornecedores#index', as: 'fornecedores'
  get 'fornecedores/:id', to: 'fornecedores#mostrar', as: 'fornecedor_mostrar'
  post 'fornecedores', to: 'fornecedores#cadastrar', as: 'fornecedor_cadastrar'
  match 'fornecedores/:id', to: 'fornecedores#alterar', as: 'fornecedor', via: [:put, :patch]
  delete 'fornecedores/:id', to: 'fornecedores#excluir', as: 'fornecedor_excluir'
  #######################
end

app/views/fornecedores_artesanal/_form.html.erb
<a href="<%= fornecedores_path %>">Lista de Fornecedores</a><br>

<form action="<%= url %>" <% if method == 'put' %> data-put-com-redirect="<%= fornecedores_path %>" <% else %> method="<%= method %>" <% end %>>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div>
    <label for="nome">Nome:</label>
    <input type="text" id="nome" value="<%= @fornecedor.nome %>" name="fornecedor[nome]" >
  </div>
  <div>
    <label for="nome">Razão Social:</label>
    <input type="text" id="nome" value="<%= @fornecedor.razao_social %>" name="fornecedor[razao_social]" required>
  </div>
  <div>
    <label for="cnpj">CNPJ:</label>
    <input type="text" id="cnpj" value="<%= @fornecedor.cnpj %>" name="fornecedor[cnpj]" required>
  </div>
  <div>
    <label for="endereco">Endereço:</label>
    <input type="text" id="endereco" value="<%= @fornecedor.endereco %>" name="fornecedor[endereco]" required>
  </div>
  <br>
  <div>
    <input type="submit" value="Salvar">
  </div>
</form>

app/views/fornecedores_artesanal/editar.html.erb
<section class="panel banner right">
  <div class="content color0 span-3-75">
    <h1>Editar Fornecedor</h1>

    <%= render "form", url: fornecedor_alterar_path(@fornecedor), method: 'put' %>

  </div>

  <div class="image filtered span-1-75" data-position="25% 25%">
    <img src="/images/pic01.jpg" alt="" />
  </div>
</section>

app/views/fornecedores_artesanal/index.html.erb
<section class="panel banner right">
  <div class="content color0 span-3-75">
    <a href="/">Voltar para home</a><br>
    <h1>Fornecedores</h1>

    <a href="<%= fornecedor_novo_path %>">Novo Fornecedor</a><br>

    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Nome</th>
          <th>Razão Social</th>
          <th>CNPJ</th>
          <th>Endereço</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @fornecedores.each do |fornecedor| %>
          <tr>
            <td><a href="<%= fornecedor_mostrar_path(fornecedor) %>"> <%= fornecedor.id %> </a></td>
            <td><%= fornecedor.nome %></td>
            <td><%= fornecedor.razao_social %></td>
            <td><%= fornecedor.cnpj %></td>
            <td><%= fornecedor.endereco %></td>
            <td>
                <a href="<%= fornecedor_editar_path(fornecedor) %>" class="btn">Alterar</a>
                <!-- a href="#" onclick="excluir('<%= fornecedor_excluir_path(fornecedor) %>', '<%= fornecedores_path %>')" class="btn">Excluir</a -->
                <a href="#" data-excluir="<%= fornecedor_excluir_path(fornecedor, format: :json) %>" class="btn">Excluir</a>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>

  <div class="image filtered span-1-75" data-position="25% 25%">
    <img src="/images/pic01.jpg" alt="" />
  </div>
</section>

app/views/fornecedores_artesanal/mostrar.html.erb
<section class="panel banner right">
  <div class="content color0 span-3-75">
    <h1>Fornecedor</h1>

    <a href="<%= fornecedores_path %>">Lista de Fornecedores</a><br>

    <div>
      Nome: <%= @fornecedor.nome %>
    </div>
    <div>
      Razão Social: <%= @fornecedor.razao_social %>
    </div>
    <div>
      CNPJ: <%= @fornecedor.cnpj %>
    </div>
    <div>
      Endereço: <%= @fornecedor.endereco %>
    </div>

  </div>

  <div class="image filtered span-1-75" data-position="25% 25%">
    <img src="/images/pic01.jpg" alt="" />
  </div>
</section>

app/views/fornecedores_artesanal/novo.html.erb
<section class="panel banner right">
  <div class="content color0 span-3-75">
    <h1>Novo Fornecedor</h1>

    <%= render "form", url: fornecedor_cadastrar_path, method: 'post' %>
  </div>

  <div class="image filtered span-1-75" data-position="25% 25%">
    <img src="/images/pic01.jpg" alt="" />
  </div>
</section>